### ISSUE TITLE
Default location?

### ISSUE THREAD

**Issue by stelliot** [actions-on-google/dialogflow-name-psychic-nodejs#3] opened 2017-05-26 12:41 UTC
I only receive Mountain View as my location? I get the location request as expected and the cloud function writes to the Firebase database but always Mountain View. Tested on Android and iOS version of the Google Assistant.

**Comment by salismt** [comment] 2017-07-16 16:05
@silvolu is there any update for this problem?

**Comment by silvolu** [comment] 2017-07-17 16:40
Hi @salismt,

Apologies for the delay in getting back to you. I think what you are experiencing might be working as intended: the location is written to the Firebase Database only the first time, and then if present is just read from there. So if you tested for the first time while in Mountain View or using the Actions on Google simulator with location set to Mountain View, that would explain it.
You can test it again by removing data from the associated Firebase DB; if you have multiple users in the db,  you can add a console.log for the user id [here](https://github.com/actions-on-google/apiai-name-psychic-nodejs/blob/master/functions/index.js#L104) to get the user key.
Let me know if the problem still persist or if I can close this bug, meanwhile I'll open a separate  discussion issue on whether we should re-think the logic of the sample to save only the name permanently.

**Comment by Canain** [comment] 2017-10-31 21:57
Closing this issue since there hasn't been more comments. Please comment on the linked issue or open another one if you have more problems.

**Closed as completed by Canain** 2017-10-31 21:57 UTC
